# Generated by Django 6.0.2 on 2026-04-17 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(choices=[('Mobile', 'Mobile Money'), ('Card', 'card'), ('Cash', 'cash')], max_length=10),
        ),
    ]
