# Generated by Django 6.0.2 on 2026-04-15 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_status',
            field=models.CharField(choices=[('availabel', 'AVAILABLE'), ('not_available', 'NOT_AVAILABLE')], default='available', max_length=20),
        ),
        migrations.AlterField(
            model_name='roomtype',
            name='name',
            field=models.CharField(max_length=20),
        ),
    ]
