# Generated by Django 6.0.2 on 2026-04-15 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_alter_room_room_status_alter_roomtype_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='roomtype',
            old_name='name',
            new_name='category',
        ),
    ]
