# Generated by Django 6.0.2 on 2026-04-15 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0003_rename_name_roomtype_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_status',
            field=models.CharField(choices=[('available', 'AVAILABLE'), ('not_available', 'NOT_AVAILABLE')], default='available', max_length=20),
        ),
    ]
