# Generated by Django 6.0.2 on 2026-04-15 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0004_alter_room_room_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_status',
            field=models.CharField(choices=[('Available', 'AVAILABLE'), ('Not_available', 'NOT_AVAILABLE')], default='available', max_length=20),
        ),
    ]
