# Generated by Django 6.0.2 on 2026-04-13 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Customer',
            new_name='Guest',
        ),
    ]
