# Generated by Django 6.0.2 on 2026-04-13 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0002_rename_customer_guest'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='guest_status',
            field=models.CharField(default='checked in', max_length=20),
        ),
    ]
